import { media } from "../media";
import type { Trainer } from "../types";

export const trainers: Trainer[] = [
  {
    id: "7a1c0f0e-0001-4c1a-9a01-000000000001",
    slug: "arjun-rao",
    name: "Arjun Rao",
    position: "Head Coach",
    specialization: "Strength & Powerlifting",
    experienceYears: 12,
    bio: "National-level powerlifter turned coach. Arjun has guided 300+ members to their first bodyweight deadlift and beyond.",
    image: media.trainers.arjun,
    certifications: ["NSCA-CSCS", "USAPL Club Coach"],
    social: { instagram: "https://instagram.com", youtube: "https://youtube.com" },
  },
  {
    id: "7a1c0f0e-0002-4c1a-9a01-000000000002",
    slug: "meera-kapoor",
    name: "Meera Kapoor",
    position: "Performance Coach",
    specialization: "HIIT & Fat Loss",
    experienceYears: 8,
    bio: "Former state-level sprinter who blends conditioning science with relentless energy. Meera runs our flagship HIIT programme.",
    image: media.trainers.meera,
    certifications: ["ACE-CPT", "Precision Nutrition L1"],
    social: { instagram: "https://instagram.com" },
  },
  {
    id: "7a1c0f0e-0003-4c1a-9a01-000000000003",
    slug: "kabir-singh",
    name: "Kabir Singh",
    position: "Senior Trainer",
    specialization: "Hypertrophy & Physique",
    experienceYears: 9,
    bio: "Competitive physique athlete focused on intelligent volume and nutrition. Kabir builds programs that make progress visible.",
    image: media.trainers.kabir,
    certifications: ["ISSA-CPT", "ISSN Sports Nutrition"],
    social: { instagram: "https://instagram.com", x: "https://x.com" },
  },
  {
    id: "7a1c0f0e-0004-4c1a-9a01-000000000004",
    slug: "zara-sheikh",
    name: "Zara Sheikh",
    position: "Boxing Coach",
    specialization: "Boxing & Conditioning",
    experienceYears: 7,
    bio: "Amateur boxing champion bringing fight-camp conditioning to every member — technique first, then intensity.",
    image: media.trainers.zara,
    certifications: ["AIBA Level 1", "NASM-CPT"],
    social: { instagram: "https://instagram.com" },
  },
  {
    id: "7a1c0f0e-0005-4c1a-9a01-000000000005",
    slug: "vikram-menon",
    name: "Vikram Menon",
    position: "Functional Specialist",
    specialization: "Functional & Sports Conditioning",
    experienceYears: 10,
    bio: "Strength coach to state cricket and football squads. Vikram specialises in speed, power and resilient athletes.",
    image: media.trainers.vikram,
    certifications: ["EXOS Performance", "FMS Level 2"],
    social: { instagram: "https://instagram.com", youtube: "https://youtube.com" },
  },
  {
    id: "7a1c0f0e-0006-4c1a-9a01-000000000006",
    slug: "ananya-iyer",
    name: "Ananya Iyer",
    position: "Mobility & Yoga Lead",
    specialization: "Mobility, Yoga & Recovery",
    experienceYears: 11,
    bio: "Physiotherapist and E-RYT 500 yoga teacher. Ananya keeps our members moving freely, recovering faster and training longer.",
    image: media.trainers.ananya,
    certifications: ["BPT", "E-RYT 500", "FRC Mobility Specialist"],
    social: { instagram: "https://instagram.com" },
  },
];

export const getTrainer = (idOrSlug: string) => trainers.find((t) => t.id === idOrSlug || t.slug === idOrSlug);
