-- Generated by scripts/generate-seed.ts — placeholder catalogue data.

insert into public.membership_plans (id, slug, name, duration_months, duration_days, price_paise, compare_at_paise, tagline, features, is_highlighted, sort_order) values
  ('9b2d0000-0000-4000-8000-000000000001', 'basic', 'Basic', 1, 30, 249900, null, 'Get started, no strings.', array['Full gym floor access', 'Locker & shower', 'Fitness assessment', 'Member app & QR check-in']::text[], false, 0),
  ('9b2d0000-0000-4000-8000-000000000002', 'standard', 'Standard', 3, 90, 649900, 749700, 'Build the habit.', array['Everything in Basic', 'Unlimited group classes', 'Monthly body composition scan', 'Starter workout plan']::text[], false, 1),
  ('9b2d0000-0000-4000-8000-000000000003', 'premium', 'Premium', 6, 180, 1199900, 1499400, 'Our most chosen plan.', array['Everything in Standard', '4 personal training sessions', 'Custom workout & diet plan', 'Recovery zone access', 'Progress tracking dashboard']::text[], true, 2),
  ('9b2d0000-0000-4000-8000-000000000004', 'elite', 'Elite', 12, 365, 1999900, 2998800, 'All in. All year.', array['Everything in Premium', '12 personal training sessions', 'Quarterly coach review', 'Guest passes (4)', 'Priority class booking', 'ATHLEX kit on joining']::text[], false, 3)
on conflict (id) do nothing;

insert into public.trainers (id, slug, name, position, specialization, experience_years, bio, image_url, certifications, social, sort_order) values
  ('7a1c0f0e-0001-4c1a-9a01-000000000001', 'arjun-rao', 'Arjun Rao', 'Head Coach', 'Strength & Powerlifting', 12, 'National-level powerlifter turned coach. Arjun has guided 300+ members to their first bodyweight deadlift and beyond.', 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=900&q=75', array['NSCA-CSCS', 'USAPL Club Coach']::text[], '{"instagram":"https://instagram.com","youtube":"https://youtube.com"}'::jsonb, 0),
  ('7a1c0f0e-0002-4c1a-9a01-000000000002', 'meera-kapoor', 'Meera Kapoor', 'Performance Coach', 'HIIT & Fat Loss', 8, 'Former state-level sprinter who blends conditioning science with relentless energy. Meera runs our flagship HIIT programme.', 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=900&q=75', array['ACE-CPT', 'Precision Nutrition L1']::text[], '{"instagram":"https://instagram.com"}'::jsonb, 1),
  ('7a1c0f0e-0003-4c1a-9a01-000000000003', 'kabir-singh', 'Kabir Singh', 'Senior Trainer', 'Hypertrophy & Physique', 9, 'Competitive physique athlete focused on intelligent volume and nutrition. Kabir builds programs that make progress visible.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=75', array['ISSA-CPT', 'ISSN Sports Nutrition']::text[], '{"instagram":"https://instagram.com","x":"https://x.com"}'::jsonb, 2),
  ('7a1c0f0e-0004-4c1a-9a01-000000000004', 'zara-sheikh', 'Zara Sheikh', 'Boxing Coach', 'Boxing & Conditioning', 7, 'Amateur boxing champion bringing fight-camp conditioning to every member — technique first, then intensity.', 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=900&q=75', array['AIBA Level 1', 'NASM-CPT']::text[], '{"instagram":"https://instagram.com"}'::jsonb, 3),
  ('7a1c0f0e-0005-4c1a-9a01-000000000005', 'vikram-menon', 'Vikram Menon', 'Functional Specialist', 'Functional & Sports Conditioning', 10, 'Strength coach to state cricket and football squads. Vikram specialises in speed, power and resilient athletes.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=75', array['EXOS Performance', 'FMS Level 2']::text[], '{"instagram":"https://instagram.com","youtube":"https://youtube.com"}'::jsonb, 4),
  ('7a1c0f0e-0006-4c1a-9a01-000000000006', 'ananya-iyer', 'Ananya Iyer', 'Mobility & Yoga Lead', 'Mobility, Yoga & Recovery', 11, 'Physiotherapist and E-RYT 500 yoga teacher. Ananya keeps our members moving freely, recovering faster and training longer.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=75', array['BPT', 'E-RYT 500', 'FRC Mobility Specialist']::text[], '{"instagram":"https://instagram.com"}'::jsonb, 5)
on conflict (id) do nothing;

insert into public.classes (id, slug, name, category, duration_min, intensity, description) values
  ('c1000000-0000-4000-8000-000000000001', 'sunrise-yoga', 'Sunrise Yoga', 'Yoga', 60, 1, 'Vinyasa flow to wake the body and focus the mind.'),
  ('c1000000-0000-4000-8000-000000000002', 'hiit-inferno', 'HIIT Inferno', 'HIIT', 40, 5, 'Zoned intervals on bikes, rowers and turf.'),
  ('c1000000-0000-4000-8000-000000000003', 'zumba-rush', 'Zumba Rush', 'Zumba', 50, 3, 'High-energy dance cardio. No experience needed.'),
  ('c1000000-0000-4000-8000-000000000004', 'barbell-club', 'Barbell Club', 'Strength', 60, 4, 'Coached compound lifts with progressive loading.'),
  ('c1000000-0000-4000-8000-000000000005', 'functional-flow', 'Functional Flow', 'Functional', 45, 3, 'Kettlebells, sleds and carries for real-world strength.'),
  ('c1000000-0000-4000-8000-000000000006', 'cardio-burn', 'Cardio Burn', 'Cardio', 45, 3, 'Steady-state and tempo intervals for your engine.'),
  ('c1000000-0000-4000-8000-000000000007', 'fight-camp', 'Fight Camp', 'Boxing', 50, 4, 'Pad work, footwork and fight conditioning.'),
  ('c1000000-0000-4000-8000-000000000008', 'mobility-lab', 'Mobility Lab', 'Mobility', 45, 1, 'Joint prep, CARs and deep stretching for recovery.')
on conflict (id) do nothing;

insert into public.class_schedules (id, class_id, trainer_id, day_of_week, start_time, end_time, room, capacity) values
  ('5c000000-0000-4000-8000-000000000001', 'c1000000-0000-4000-8000-000000000001', '7a1c0f0e-0006-4c1a-9a01-000000000006', 0, '06:00', '07:00', 'Studio 1', 20),
  ('5c000000-0000-4000-8000-000000000002', 'c1000000-0000-4000-8000-000000000002', '7a1c0f0e-0002-4c1a-9a01-000000000002', 0, '07:15', '07:55', 'Turf', 18),
  ('5c000000-0000-4000-8000-000000000003', 'c1000000-0000-4000-8000-000000000004', '7a1c0f0e-0001-4c1a-9a01-000000000001', 0, '18:00', '19:00', 'Platform Zone', 12),
  ('5c000000-0000-4000-8000-000000000004', 'c1000000-0000-4000-8000-000000000007', '7a1c0f0e-0004-4c1a-9a01-000000000004', 0, '19:30', '20:20', 'Combat Room', 16),
  ('5c000000-0000-4000-8000-000000000005', 'c1000000-0000-4000-8000-000000000005', '7a1c0f0e-0005-4c1a-9a01-000000000005', 1, '06:30', '07:15', 'Turf', 16),
  ('5c000000-0000-4000-8000-000000000006', 'c1000000-0000-4000-8000-000000000003', '7a1c0f0e-0002-4c1a-9a01-000000000002', 1, '07:30', '08:20', 'Studio 1', 25),
  ('5c000000-0000-4000-8000-000000000007', 'c1000000-0000-4000-8000-000000000006', '7a1c0f0e-0002-4c1a-9a01-000000000002', 1, '18:30', '19:15', 'Cardio Deck', 20),
  ('5c000000-0000-4000-8000-000000000008', 'c1000000-0000-4000-8000-000000000008', '7a1c0f0e-0006-4c1a-9a01-000000000006', 1, '20:00', '20:45', 'Studio 2', 15),
  ('5c000000-0000-4000-8000-000000000009', 'c1000000-0000-4000-8000-000000000004', '7a1c0f0e-0001-4c1a-9a01-000000000001', 2, '06:00', '07:00', 'Platform Zone', 12),
  ('5c000000-0000-4000-8000-000000000010', 'c1000000-0000-4000-8000-000000000002', '7a1c0f0e-0002-4c1a-9a01-000000000002', 2, '07:15', '07:55', 'Turf', 18),
  ('5c000000-0000-4000-8000-000000000011', 'c1000000-0000-4000-8000-000000000007', '7a1c0f0e-0004-4c1a-9a01-000000000004', 2, '18:00', '18:50', 'Combat Room', 16),
  ('5c000000-0000-4000-8000-000000000012', 'c1000000-0000-4000-8000-000000000001', '7a1c0f0e-0006-4c1a-9a01-000000000006', 2, '19:15', '20:15', 'Studio 1', 20),
  ('5c000000-0000-4000-8000-000000000013', 'c1000000-0000-4000-8000-000000000005', '7a1c0f0e-0005-4c1a-9a01-000000000005', 3, '06:30', '07:15', 'Turf', 16),
  ('5c000000-0000-4000-8000-000000000014', 'c1000000-0000-4000-8000-000000000006', '7a1c0f0e-0003-4c1a-9a01-000000000003', 3, '07:30', '08:15', 'Cardio Deck', 20),
  ('5c000000-0000-4000-8000-000000000015', 'c1000000-0000-4000-8000-000000000004', '7a1c0f0e-0003-4c1a-9a01-000000000003', 3, '18:30', '19:30', 'Platform Zone', 12),
  ('5c000000-0000-4000-8000-000000000016', 'c1000000-0000-4000-8000-000000000003', '7a1c0f0e-0002-4c1a-9a01-000000000002', 3, '19:45', '20:35', 'Studio 1', 25),
  ('5c000000-0000-4000-8000-000000000017', 'c1000000-0000-4000-8000-000000000002', '7a1c0f0e-0002-4c1a-9a01-000000000002', 4, '06:00', '06:40', 'Turf', 18),
  ('5c000000-0000-4000-8000-000000000018', 'c1000000-0000-4000-8000-000000000001', '7a1c0f0e-0006-4c1a-9a01-000000000006', 4, '07:00', '08:00', 'Studio 1', 20),
  ('5c000000-0000-4000-8000-000000000019', 'c1000000-0000-4000-8000-000000000007', '7a1c0f0e-0004-4c1a-9a01-000000000004', 4, '18:00', '18:50', 'Combat Room', 16),
  ('5c000000-0000-4000-8000-000000000020', 'c1000000-0000-4000-8000-000000000008', '7a1c0f0e-0006-4c1a-9a01-000000000006', 4, '19:00', '19:45', 'Studio 2', 15),
  ('5c000000-0000-4000-8000-000000000021', 'c1000000-0000-4000-8000-000000000004', '7a1c0f0e-0001-4c1a-9a01-000000000001', 5, '08:00', '09:00', 'Platform Zone', 12),
  ('5c000000-0000-4000-8000-000000000022', 'c1000000-0000-4000-8000-000000000003', '7a1c0f0e-0002-4c1a-9a01-000000000002', 5, '09:15', '10:05', 'Studio 1', 25),
  ('5c000000-0000-4000-8000-000000000023', 'c1000000-0000-4000-8000-000000000005', '7a1c0f0e-0005-4c1a-9a01-000000000005', 5, '10:30', '11:15', 'Turf', 16),
  ('5c000000-0000-4000-8000-000000000024', 'c1000000-0000-4000-8000-000000000006', '7a1c0f0e-0003-4c1a-9a01-000000000003', 5, '17:00', '17:45', 'Cardio Deck', 20),
  ('5c000000-0000-4000-8000-000000000025', 'c1000000-0000-4000-8000-000000000001', '7a1c0f0e-0006-4c1a-9a01-000000000006', 6, '08:00', '09:00', 'Studio 1', 20),
  ('5c000000-0000-4000-8000-000000000026', 'c1000000-0000-4000-8000-000000000008', '7a1c0f0e-0006-4c1a-9a01-000000000006', 6, '09:30', '10:15', 'Studio 2', 15)
on conflict (id) do nothing;

insert into public.gallery_categories (slug, name, sort_order) values
  ('gym', 'Gym', 0),
  ('equipment', 'Equipment', 1),
  ('trainers', 'Trainers', 2),
  ('workouts', 'Workouts', 3),
  ('events', 'Events', 4),
  ('members', 'Members', 5),
  ('transformations', 'Transformations', 6)
on conflict (slug) do nothing;

insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000001', id, 'Main training floor', 'image', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=75', null, 1600, 1067, 0, 'published' from public.gallery_categories where slug = 'gym'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000002', id, 'Strength platforms', 'image', 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1400&q=75', null, 1200, 1600, 1, 'published' from public.gallery_categories where slug = 'equipment'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000003', id, 'Night session', 'image', 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1400&q=75', null, 1600, 1067, 2, 'published' from public.gallery_categories where slug = 'gym'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000004', id, 'Plate wall', 'image', 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=1400&q=75', null, 1600, 1200, 3, 'published' from public.gallery_categories where slug = 'equipment'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000005', id, 'Deadlift day', 'image', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=75', null, 1200, 1600, 4, 'published' from public.gallery_categories where slug = 'workouts'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000006', id, 'Arm day with Kabir', 'image', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1400&q=75', null, 1600, 1067, 5, 'published' from public.gallery_categories where slug = 'trainers'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000007', id, 'Coached dumbbell work', 'image', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=75', null, 1200, 1500, 6, 'published' from public.gallery_categories where slug = 'members'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000008', id, 'Fight Camp', 'video', 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1400&q=75', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 1600, 1067, 7, 'published' from public.gallery_categories where slug = 'events'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000009', id, 'Kettlebell complex', 'image', 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1400&q=75', null, 1600, 1200, 8, 'published' from public.gallery_categories where slug = 'workouts'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000010', id, 'Community Saturday', 'image', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=75', null, 1600, 1067, 9, 'published' from public.gallery_categories where slug = 'events'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000011', id, 'Barbell club', 'image', 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1400&q=75', null, 1200, 1600, 10, 'published' from public.gallery_categories where slug = 'members'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000012', id, 'Turf & sleds', 'image', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=1400&q=75', null, 1600, 1067, 11, 'published' from public.gallery_categories where slug = 'gym'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000013', id, 'Rope conditioning', 'image', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1400&q=75', null, 1600, 1200, 12, 'published' from public.gallery_categories where slug = 'workouts'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000014', id, '16-week transformation', 'image', 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=1400&q=75', null, 1200, 1600, 13, 'published' from public.gallery_categories where slug = 'transformations'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000015', id, 'Cardio deck', 'video', 'https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=1400&q=75', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', 1600, 1067, 14, 'published' from public.gallery_categories where slug = 'equipment'
on conflict (id) do nothing;
insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)
select '6a000000-0000-4000-8000-000000000016', id, 'Recomp: 12 weeks', 'image', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1400&q=75', null, 1600, 1200, 15, 'published' from public.gallery_categories where slug = 'transformations'
on conflict (id) do nothing;

insert into public.testimonials (name, image_url, rating, review, transformation, member_since, sort_order) values
  ('Sneha Reddy', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=75', 5, 'The coaching here is on a different level. Every session has a purpose, every coach knows my numbers. I''ve never been this consistent.', '−9 kg in 14 weeks', '2023', 0),
  ('Karan Malhotra', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=75', 5, 'Premium facility, zero ego. The QR check-in, the app, the recovery zone — it feels like a members'' club built for people who actually train.', 'Squat 100 → 170 kg', '2022', 1),
  ('Aisha Khan', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=75', 5, 'Fight Camp with Zara changed how I train. I''m fitter at 38 than I was at 25 and I actually look forward to 6 AM.', 'Resting HR 78 → 58', '2024', 2),
  ('Nikhil Verma', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=75', 4, 'Signed up for the Premium plan and the custom diet + workout plan paid for itself in two months. Clean, organised and motivating.', '+6 kg lean mass', '2023', 3),
  ('Divya Menon', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=75', 5, 'Ananya''s mobility sessions fixed a back issue I had for years. The whole team genuinely cares about how you move.', 'Pain-free in 8 weeks', '2021', 4)
on conflict (id) do nothing;

insert into public.blog_posts (slug, title, excerpt, category, cover_url, body, author, read_minutes, published_at, status) values
  ('progressive-overload-explained', 'Progressive Overload, Explained Without the Bro Science', 'The single principle behind every strength gain — and five practical ways to apply it this week.', 'Workout', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=75', 'Your body adapts to exactly what you ask of it — and nothing more. Progressive overload is simply the practice of asking for a little more over time.

The most obvious lever is load: add 1–2.5 kg to your main lifts when you hit the top of your rep range with clean technique. But load is just one of five levers.

Reps, sets, density (doing the same work in less time) and range of motion are all valid ways to progress. Rotate them and you''ll keep moving forward for years instead of weeks.

Track everything. If it isn''t written down, you''re guessing — and guessing is how plateaus start. Your ATHLEX dashboard logs every session so you always know what ''more'' looks like.', 'Arjun Rao', 6, '2026-09-12T00:00:00.000Z', 'published'),
  ('protein-for-indian-diets', 'Hitting Your Protein Target on an Indian Diet', 'Dal alone won''t cut it. Here''s a realistic, vegetarian-friendly way to eat 1.6 g/kg every day.', 'Nutrition', 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=75', 'Most active adults do well on 1.6–2.2 g of protein per kg of bodyweight. For a 70 kg person that''s 110–150 g a day — far more than a typical plate delivers.

Build every meal around a protein anchor: paneer, tofu, eggs, chicken, fish, Greek yoghurt or soya chunks. Then add dal and grains as supporting players, not the main event.

Whey or plant protein is a convenient tool, not a requirement. One scoop closes the gap for most people.', 'Kabir Singh', 7, '2026-09-02T00:00:00.000Z', 'published'),
  ('fat-loss-without-crash-diets', 'Fat Loss Without Crash Diets', 'A moderate deficit, lots of steps and heavy lifting. Boring? Yes. Effective? Absolutely.', 'Weight Loss', 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1200&q=75', 'Aggressive deficits work — briefly. Then hunger, fatigue and muscle loss catch up. Aim for 0.5–1% of bodyweight lost per week.

Keep lifting heavy to signal your body to retain muscle, walk 8–10k steps daily and prioritise sleep. Use our calorie calculator to set your starting target.', 'Meera Kapoor', 5, '2026-08-21T00:00:00.000Z', 'published'),
  ('hypertrophy-volume-guide', 'How Much Volume Do You Really Need to Grow?', 'Sets per muscle per week, proximity to failure and why more isn''t always better.', 'Muscle Building', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=75', 'Research suggests 10–20 hard sets per muscle group per week is the sweet spot for most lifters.

''Hard'' is the key word: finish most sets 1–3 reps shy of failure. Junk volume adds fatigue, not muscle.', 'Kabir Singh', 8, '2026-08-08T00:00:00.000Z', 'published'),
  ('meal-prep-sunday', 'The 60-Minute Sunday Meal Prep', 'Five containers, three proteins, zero stress. A coach-approved template for busy weeks.', 'Fitness Tips', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=75', 'Cook two proteins, one grain and roast a tray of vegetables. Portion into containers and you''re set for the working week.', 'Meera Kapoor', 4, '2026-07-27T00:00:00.000Z', 'published'),
  ('sleep-is-a-performance-drug', 'Sleep Is the Most Underrated Performance Drug', 'Why 7–9 hours will do more for your physique than any supplement on the shelf.', 'Lifestyle', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=75', 'Growth hormone release, appetite regulation and training recovery all depend on consistent, quality sleep.

Keep a fixed wake time, dim screens an hour before bed and keep your room cool and dark.', 'Ananya Iyer', 5, '2026-07-14T00:00:00.000Z', 'published')
on conflict (slug) do nothing;

insert into public.coupons (code, description, discount_type, discount_value, max_redemptions) values
  ('WELCOME10', '10% off for new members', 'percent', 10, 500)
on conflict (code) do nothing;

insert into public.settings (key, value) values
  ('gym', '{"name":"ATHLEX","phone":"+91 98765 43210","email":"hello@athlex.fit","gst_number":"","attendance_window_minutes":1}'::jsonb),
  ('notifications', '{"email":true,"whatsapp":true,"sms":false,"reminder_hours_before_class":2,"expiry_reminder_days":[7,3,1]}'::jsonb)
on conflict (key) do nothing;

-- Promote your first admin after signing up:
-- update public.users set role = 'admin' where email = 'you@yourgym.com';
