/**
 * Generates supabase/seed.sql from the placeholder content in src/lib/content.
 * Run: npx tsx scripts/generate-seed.ts > supabase/seed.sql
 * Edit the content files (or the admin console) to replace with real gym data.
 */
import { blogPosts, classSchedules, classTypes, galleryCategories, galleryItems, plans, testimonials, trainers } from "../src/lib/content";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const insert = (table: string, rows: Record<string, unknown>[], conflict = "id") => {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  return `insert into public.${table} (${cols.join(", ")}) values\n${rows.map((r) => `  (${cols.map((c) => q(r[c])).join(", ")})`).join(",\n")}\non conflict (${conflict}) do nothing;\n\n`;
};

let sql = "-- Generated by scripts/generate-seed.ts — placeholder catalogue data.\n\n";
sql += insert("membership_plans", plans.map((p, i) => ({ id: p.id, slug: p.slug, name: p.name, duration_months: p.durationMonths, duration_days: p.durationDays, price_paise: p.price, compare_at_paise: p.compareAt ?? null, tagline: p.tagline, features: p.features, is_highlighted: Boolean(p.highlighted), sort_order: i })));
sql += insert("trainers", trainers.map((t, i) => ({ id: t.id, slug: t.slug, name: t.name, position: t.position, specialization: t.specialization, experience_years: t.experienceYears, bio: t.bio, image_url: t.image, certifications: t.certifications, social: t.social, sort_order: i })));
sql += insert("classes", classTypes.map((c) => ({ id: c.id, slug: c.slug, name: c.name, category: c.category, duration_min: c.durationMin, intensity: c.intensity, description: c.description })));
sql += insert("class_schedules", classSchedules.map((s) => ({ id: s.id, class_id: s.classId, trainer_id: s.trainerId, day_of_week: s.day, start_time: s.start, end_time: s.end, room: s.room, capacity: s.capacity })));
const cats = galleryCategories.filter((c) => c.value !== "all");
sql += insert("gallery_categories", cats.map((c, i) => ({ slug: c.value, name: c.label, sort_order: i })), "slug");
sql += galleryItems
  .map((g, i) => `insert into public.gallery (id, category_id, title, kind, url, video_url, width, height, sort_order, status)\nselect ${q(g.id)}, id, ${q(g.title)}, ${q(g.kind)}, ${q(g.src)}, ${q(g.videoUrl ?? null)}, ${g.width}, ${g.height}, ${i}, 'published' from public.gallery_categories where slug = ${q(g.category)}\non conflict (id) do nothing;\n`)
  .join("") + "\n";
sql += insert("testimonials", testimonials.map((t, i) => ({ name: t.name, image_url: t.image, rating: t.rating, review: t.review, transformation: t.transformation, member_since: t.memberSince, sort_order: i })), "id");
sql += insert("blog_posts", blogPosts.map((b) => ({ slug: b.slug, title: b.title, excerpt: b.excerpt, category: b.category, cover_url: b.image, body: b.body.join("\n\n"), author: b.author, read_minutes: b.readMinutes, published_at: new Date(b.date).toISOString(), status: "published" })), "slug");
sql += insert("coupons", [{ code: "WELCOME10", description: "10% off for new members", discount_type: "percent", discount_value: 10, max_redemptions: 500 }], "code");
sql += insert("settings", [
  { key: "gym", value: { name: "ATHLEX", phone: "+91 98765 43210", email: "hello@athlex.fit", gst_number: "", attendance_window_minutes: 1 } },
  { key: "notifications", value: { email: true, whatsapp: true, sms: false, reminder_hours_before_class: 2, expiry_reminder_days: [7, 3, 1] } },
], "key");
sql += `-- Promote your first admin after signing up:\n-- update public.users set role = 'admin' where email = 'you@yourgym.com';\n`;
process.stdout.write(sql);
